version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=pacifical_task
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    networks:
      - mynetwork

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pacifical_task
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
